{{- $dupValues := deepCopy .Values -}}
{{- $dupValues := omit $dupValues "partials" -}}
{{- range $key, $value := $dupValues -}}
  {{- if kindIs "map" $value -}}
    {{- if and (hasKey $value "global") (ne $key "configs" ) -}}
      {{- $dupValues := set $dupValues $key (unset $value "global") -}}
    {{- end -}}
    {{- if hasKey $value "partials" -}}
      {{- $dupValues := set $dupValues $key (unset $value "partials") -}}
    {{- end -}}
    {{- if hasKey $value "KeyPEM" -}}
      {{- $dupValues := set $dupValues $key (unset $value "keyPEM") -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- /* Unset known private fields */ -}}
{{- if $dupValues.identity.issuer.tls.keyPEM -}}
  {{- $_ := set $dupValues.identity.issuer.tls "keyPEM" "" -}}
{{- end -}}
{{- if $dupValues.profileValidator.keyPEM -}}
  {{- $_ := set $dupValues.profileValidator "keyPEM" "" -}}
{{- end -}}
{{- if $dupValues.proxyInjector.keyPEM -}}
  {{- $_ := set $dupValues.proxyInjector "keyPEM" "" -}}
{{- end -}}
---
###
### linkerd state
###
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-state
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |-
    {{- toYaml $dupValues | trim | nindent 4 -}}