dependencies:
- name: partials
  version: 0.1.0
  repository: file://../partials
- name: prometheus
  version: 0.1.0
  repository: file://../add-ons/prometheus
  condition: prometheus.enabled
- name: grafana
  version: 0.1.0
  repository: file://../add-ons/grafana
  condition: grafana.enabled
- name: publicApi
  version: 0.1.0
  repository: file://../add-ons/publicApi
  condition: publicApi.enabled
- name: tracing
  version: 0.1.0
  repository: file://../add-ons/tracing
  condition: tracing.enabled
